schemaVersion: "1.2"
spec:
  inbound:
    - name: Your WebSocket Serviceskip
      TrivyScan: false
      port: 8080
      type: WS
      networkVisibility: Public
      context: /your-websocket-context
  env:
    - from: START_COMMAND
      to: npm run dev
    - from: BUILD_COMMAND
      to: yarn --frozen-lockfile install;yarn build
