name: Clean Redeploy Trigger

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '45 2 * * *'
    - cron: '30 5 * * *'
    - cron: '15 8 * * *'
    - cron: '0 11 * * *'
    - cron: '45 13 * * *'
    - cron: '30 16 * * *'
    - cron: '15 19 * * *'
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  deploy-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Force push same commit (no new history)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # get current HEAD commit hash
          CURRENT_SHA=$(git rev-parse HEAD)

          # force-push HEAD back to itself
          git push origin $CURRENT_SHA:main --force
