name: Clean Redeploy Trigger

on:
  schedule:
    # Trigger redeploy
    - cron: '0 0 * * *'     # midnight
    - cron: '45 2 * * *'
    - cron: '30 5 * * *'
    - cron: '15 8 * * *'
    - cron: '0 11 * * *'
    - cron: '45 13 * * *'
    - cron: '30 16 * * *'
    - cron: '15 19 * * *'
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commit and push trigger
        run: |
          echo "Triggered at $(date -u) — $RANDOM" > .choreo-redeploy-trigger.txt
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .choreo-redeploy-trigger.txt
          git commit -m "chore: trigger redeploy"
          git push
