name: Unzip, Flatten, and Commit

on:
  push:
    branches:
      - main

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip the archive
        run: unzip -o BotDataBase.zip

      - name: Move contents to root (excluding .git and .github)
        run: |
          shopt -s dotglob extglob  # include hidden files & extended globbing
          EXTRACTED_DIR=$(find . -mindepth 1 -maxdepth 1 -type d ! -name ".git" ! -name ".github" | head -n 1)
          echo "Detected extracted folder: $EXTRACTED_DIR"
          mv "$EXTRACTED_DIR"/!(.git|.github) .
          rm -rf "$EXTRACTED_DIR"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push unzipped content
        run: |
          git add .
          git commit -m "Unzipped and moved contents of archive to root (excluding .git and .github)" || echo "No changes to commit"
          git push
